version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/unipishop
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
